/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 gallery.glb --transform
*/

import React, { useRef } from "react";
import { useGLTF, Html } from "@react-three/drei";
import { useControls } from "leva";
import * as THREE from "three";
export function Model(props) {
  const { nodes, materials } = useGLTF("/gallery-transformed.glb");

  const { position, rotation } = useControls("HTML", {
    position: {
      value: [0, 155, 199],

      step: 0.1,
    },
    rotation: {
      value: [0, 0, 0],
      step: 0.1,
    },
  });
  return (
    <group position={props.position} {...props} dispose={null}>
      <mesh
        geometry={nodes.Roof_bars002.geometry}
        material={materials["Bars 3"]}
        position={[20.31, 4.061, -23.334]}
        scale={[8.503, 0.064, 0.064]}
      />
      <mesh
        geometry={nodes.Roof_bars003.geometry}
        material={materials["Bar 4"]}
        position={[13.283, 4.106, 7.796]}
        scale={[8.503, 0.064, 0.064]}
      />
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials.ALLWALLS}
        scale={[1, 0.051, 1]}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials["entrance wall"]}
        position={[18.468, 1.917, -0.38]}
        scale={[1.927, 2.133, 1.927]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials["white tri wall"]}
        position={[36.184, 0.941, -12.708]}
        scale={[2.783, 1, 1]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials.whitep}
        position={[44.144, 0.932, -12.249]}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={materials["wall behind"]}
        position={[28.878, 0.946, -18.355]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={materials["podium car"]}
        position={[0, 0.905, 0]}
      />
      <mesh
        geometry={nodes.Cube007.geometry}
        material={materials["bACK WALL "]}
        position={[-3.674, 0.909, -8.108]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Cube008.geometry}
        material={materials["tEMP WALL"]}
        position={[14.74, 0.988, -17.744]}
        rotation={[0, -1.571, 0]}
        scale={[1, 1.119, 1]}
      />
      <group position={[10.598, 0.919, -8.342]} scale={[2.27, 0.992, 2.27]}>
        <mesh
          geometry={nodes.Cube013_1.geometry}
          material={materials["White inside wall"]}
        />
        <mesh
          geometry={nodes.Cube013_2.geometry}
          material={materials["inside wall skirt"]}
        />
      </group>
      <mesh
        geometry={nodes.Floor.geometry}
        material={materials["Floor wood"]}
        scale={[1, 0.051, 1]}
      />
      <mesh
        geometry={nodes.roof.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Roof_bars.geometry}
        material={materials["bars one"]}
        position={[35.676, 4.101, -8.493]}
        scale={[8.503, 0.064, 0.064]}
      />
      <mesh
        geometry={nodes.Roof_bars001.geometry}
        material={materials["bars 2"]}
        position={[2.362, 4.101, -3.951]}
        scale={[8.503, 0.064, 0.064]}
      />
      <mesh
        geometry={nodes.Cube010.geometry}
        material={materials["Black paint"]}
        position={[12.4, 9.989, -38.496]}
      />
      <group
        position={[-4.87, 3.838, -3.836]}
        rotation={[0, 0.407, 0]}
        scale={[0.181, 0.037, 0.181]}
      >
        <mesh
          geometry={nodes.Cylinder035_1.geometry}
          material={materials.Silver}
        />
        <mesh
          geometry={nodes.Cylinder035_2.geometry}
          material={materials["Spot light emission"]}
        />
      </group>
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials["outer path"]}
        position={[18.454, -0.021, 7.847]}
      />
      <mesh geometry={nodes.Cube012.geometry} material={materials.SKIRTING} />
      <mesh
        geometry={nodes.Cube013.geometry}
        material={materials["skirting entrance box"]}
        position={[18.468, 0.061, -0.38]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1.943, -0.172, -1.943]}
      />
      <mesh
        geometry={
          nodes.Female___Woman_03___Renderpeople_No_Reflectance.geometry
        }
        material={materials["Janna - Renderpeople"]}
        position={[23.324, -0.059, -20.097]}
        rotation={[Math.PI / 2, 0, -3.127]}
        scale={0.014}
      />
      <group position={[16.263, 2.121, -0.017]} scale={[0.026, 1.315, 2.029]}>
        <mesh
          geometry={nodes.Cube027_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Cube027_2.geometry}
          material={materials.canavas}
        />
      </group>
      <mesh
        geometry={nodes.Cube019.geometry}
        material={materials["Material.003"]}
        position={[9.44, 2.031, -7.104]}
        rotation={[0, -0.422, 0]}
        scale={[1.487, 1.487, 0.028]}
      />
      <group position={[16.467, 2.206, 8.899]} scale={[0.024, 1.778, 1.292]}>
        <mesh
          geometry={nodes.Cube029_1.geometry}
          material={materials["white wall"]}
        />
        <mesh
          geometry={nodes.Cube029_2.geometry}
          material={materials["Motor logos"]}
        />
      </group>
      <mesh
        geometry={nodes.Cube021.geometry}
        material={materials["Archi 2"]}
        position={[24.156, 2.181, 13.967]}
        rotation={[0, -0.051, -Math.PI]}
        scale={[-2.354, -1.502, -0.034]}
      />
      <mesh
        geometry={nodes.Cube022.geometry}
        material={materials["Archi 3"]}
        position={[30.049, 2.181, 14.249]}
        rotation={[0, -0.051, -Math.PI]}
        scale={[-2.354, -1.502, -0.034]}
      />
      <mesh
        geometry={nodes.Cube023.geometry}
        material={materials["archi 4"]}
        position={[36.065, 2.181, 11.683]}
        rotation={[0, 0.744, -Math.PI]}
        scale={[-2.354, -1.502, -0.034]}
      />
      <mesh
        geometry={nodes.Cube024.geometry}
        material={materials["Archi 5"]}
        position={[40.877, 2.181, 7.242]}
        rotation={[0, 0.744, -Math.PI]}
        scale={[-2.354, -1.502, -0.034]}
      />
      <mesh
        geometry={nodes.Cube025.geometry}
        material={materials["archi 1"]}
        position={[20.516, 2.181, 10.139]}
        rotation={[Math.PI, -1.562, 0]}
        scale={[-2.354, -1.502, -0.034]}
      />
      <mesh
        geometry={nodes.Cube026.geometry}
        material={materials["Archi 6"]}
        position={[45.123, 2.181, -0.31]}
        rotation={[-Math.PI, 1.566, 0]}
        scale={[-2.354, -1.502, -0.034]}
      />
      <mesh
        geometry={nodes.Cube027.geometry}
        material={materials["Archi 7"]}
        position={[45.071, 2.181, -7.191]}
        rotation={[-Math.PI, 1.566, 0]}
        scale={[-2.354, -1.502, -0.034]}
      />
      <mesh
        geometry={nodes.Cube028.geometry}
        material={materials["aRCHI 8"]}
        position={[36.27, 2.181, -11.606]}
        rotation={[Math.PI, 0, 0]}
        scale={[-2.354, -1.502, -0.034]}
      />
      <mesh
        geometry={nodes.Cube029.geometry}
        material={materials["Archi 9"]}
        position={[20.214, 2.181, 0.614]}
        rotation={[Math.PI, -Math.PI / 2, 0]}
        scale={[-2.354, -1.502, -0.034]}
      />
      <mesh
        geometry={nodes.Poster_1.geometry}
        material={materials["Car poster 1"]}
        position={[3.614, 0, 0]}
      />
      <mesh
        geometry={nodes.Poster2.geometry}
        material={materials["Poster 2"]}
        position={[26.231, 1.916, -28.711]}
        scale={[1, 1, 0.021]}
      />
      <mesh
        geometry={nodes.Poster_3.geometry}
        material={materials["Poster 3"]}
        position={[23.08, 2.071, -28.703]}
        scale={[1.161, 1.161, 0.028]}
      />
      <mesh
        geometry={nodes.poster_4.geometry}
        material={materials["Poster 4"]}
        position={[19.002, 1.989, -27.472]}
        rotation={[0, -0.633, 0]}
        scale={[0.036, 1.363, 1]}
      />
      <mesh
        geometry={nodes.Poster_5.geometry}
        material={materials["bny art 5"]}
        position={[17.098, 2.075, -24.792]}
        rotation={[0, -0.619, 0]}
        scale={[0.028, 0.628, 1]}
      />
      <mesh
        geometry={nodes.Cube015.geometry}
        material={materials.Luxes}
        position={[8.222, 2.105, 15.625]}
        scale={[3.769, 1, 0.046]}
      />
      <mesh
        geometry={nodes.Cube016.geometry}
        material={materials["rMA MOTORS"]}
        position={[15.051, 2, 13.249]}
        rotation={[0, -0.568, 0]}
        scale={[0.025, 1.137, 1.137]}
      />
      <mesh
        geometry={nodes.Cube014.geometry}
        material={materials["Abny art 6"]}
        position={[14.54, 2.249, -19.108]}
        scale={[0.033, 1, 1]}
      />
      <group
        position={[4.22, 0.39, 1.584]}
        rotation={[0, 0.263, 0]}
        scale={1.418}
      >
        <mesh
          geometry={nodes.Sketchup_1.geometry}
          material={materials.Material}
        />
        <mesh
          geometry={nodes.Sketchup_2.geometry}
          material={materials["Carbon Texture3"]}
        />
        <mesh
          geometry={nodes.Sketchup_3.geometry}
          material={materials["body 1"]}
        />
        <mesh geometry={nodes.Sketchup_4.geometry} material={materials.body1} />
        <mesh geometry={nodes.Sketchup_5.geometry} material={materials["*1"]} />
      </group>
      <mesh
        geometry={nodes["G-__555780"].geometry}
        material={materials["[Color_002]3"]}
        position={[4.434, 0.927, 8.884]}
        rotation={[0, -1.308, 0]}
        scale={1.379}
      />
      <mesh
        geometry={nodes["G-__555789"].geometry}
        material={materials["[Color_008]"]}
        position={[4.482, 1.078, 8.877]}
        rotation={[Math.PI / 2, 0, -0.263]}
        scale={1.379}
      />
      <mesh
        geometry={nodes["G-__555798"].geometry}
        material={materials["[Color_A01]"]}
        position={[4.495, 1.076, 8.873]}
        rotation={[Math.PI / 2, 0, -0.263]}
        scale={1.379}
      />
      <mesh
        geometry={nodes.LEX_GS350_13.geometry}
        material={materials["[Color B06]"]}
        position={[3.381, 0.383, 9.207]}
        rotation={[0, 0.263, 0]}
        scale={58.799}
      />
      <mesh
        geometry={nodes.black.geometry}
        material={materials.Material5}
        position={[3.763, 0.661, 5.314]}
        rotation={[0, 0.263, 0]}
        scale={58.799}
      />
      <mesh
        geometry={nodes["black_glas#2"].geometry}
        material={materials["[Translucent Glass Gray]"]}
        position={[3.763, 0.661, 5.314]}
        rotation={[0, 0.263, 0]}
        scale={58.799}
      />
      <group
        position={[3.763, 0.661, 5.314]}
        rotation={[0, 0.263, 0]}
        scale={58.799}
      >
        <mesh
          geometry={nodes["black#1_1"].geometry}
          material={materials.Material5}
        />
        <mesh
          geometry={nodes["black#1_2"].geometry}
          material={materials["*2"]}
        />
      </group>
      <mesh
        geometry={nodes["textured_r#1"].geometry}
        material={materials["*7"]}
        position={[3.763, 0.661, 5.314]}
        rotation={[0, 0.263, 0]}
        scale={58.799}
      />
      <mesh
        geometry={nodes["G-__555870"].geometry}
        material={materials["*4"]}
        position={[3.818, 1.589, 1.899]}
        rotation={[0, 0.263, 0]}
        scale={58.799}
      />
      <group
        position={[3.763, 0.661, 5.314]}
        rotation={[0, 0.263, 0]}
        scale={58.799}
      >
        <mesh
          geometry={nodes["textured_r#4_1"].geometry}
          material={materials["*3"]}
        />
        <mesh
          geometry={nodes["textured_r#4_2"].geometry}
          material={materials["<YellowGreen>"]}
        />
      </group>
      <group
        position={[3.763, 0.661, 5.314]}
        rotation={[0, 0.263, 0]}
        scale={58.799}
      >
        <mesh
          geometry={nodes["chrome_2#1_1"].geometry}
          material={materials["*1"]}
        />
        <mesh
          geometry={nodes["chrome_2#1_2"].geometry}
          material={materials.body1}
        />
      </group>
      {/* Add text somewhere around here */}
      <sprite
        onClick={() => (props.toolTipRef.current.style.display = "flex")}
        position={[6.35, 1.5, 9.5]}
        scale={[0.5, 0.5, 0.5]}
        onPointerOver={(e) => (document.body.style.cursor = "pointer")}
        onPointerOut={(e) => (document.body.style.cursor = "auto")}
      >
        <spriteMaterial
          attach='material'
          map={new THREE.TextureLoader().load("/tooltip.png")}
        />
      </sprite>

      <mesh
        geometry={nodes.RIMS.geometry}
        material={materials["Cart rim"]}
        position={[4.444, 0.884, 3.186]}
        rotation={[0, 0.263, 0]}
        scale={58.799}
      />
      <mesh
        geometry={nodes.lights_gla.geometry}
        material={materials.glass1}
        position={[3.763, 0.661, 5.314]}
        rotation={[0, 0.263, 0]}
        scale={58.799}
      />
      <group
        position={[3.763, 0.661, 5.314]}
        rotation={[0, 0.263, 0]}
        scale={58.799}
      >
        <mesh
          geometry={nodes["textured_r#2_1"].geometry}
          material={materials["[Mirror 02]1"]}
        />
        <mesh
          geometry={nodes["textured_r#2_2"].geometry}
          material={materials["Turn Signal Reflector"]}
        />
      </group>
      <mesh
        geometry={nodes["Group#11"].geometry}
        material={materials["[Mirror 02]"]}
        position={[3.426, 1.626, 2]}
        rotation={[0, 0.263, 0]}
        scale={58.799}
      />
      <mesh
        geometry={nodes.reverse_li.geometry}
        material={materials["[Mirror 02]"]}
        position={[3.763, 0.661, 5.314]}
        rotation={[0, 0.263, 0]}
        scale={58.799}
      />
      <mesh
        geometry={nodes.window01001.geometry}
        material={materials.window1}
        position={[3.763, 0.661, 5.314]}
        rotation={[-Math.PI, -0.263, 0]}
        scale={-58.799}
      />
      <mesh
        geometry={nodes.tire003.geometry}
        material={materials.tyers}
        position={[2.106, 0.884, 3.816]}
        rotation={[-Math.PI, -0.263, 0]}
        scale={-58.799}
      />
      <group
        position={[37.801, 0.385, -8.788]}
        rotation={[0, Math.PI / 2, 0]}
        scale={1.319}
      >
        <mesh
          geometry={nodes["G-__555807002_1"].geometry}
          material={materials["Bench - Seat"]}
        />
        <mesh
          geometry={nodes["G-__555807002_2"].geometry}
          material={materials["Bench - Metal"]}
        />
      </group>
      <mesh
        geometry={nodes.Sketchup002.geometry}
        material={materials["sculpture white"]}
        position={[30.199, -0.45, -0.225]}
        scale={0.742}
      />
      <mesh
        geometry={nodes.Sketchup003.geometry}
        material={materials["sqaure bench"]}
        position={[23.196, 0.226, -20.887]}
        scale={1.677}
      />
      <group
        position={[21.162, 1.313, -2.417]}
        rotation={[0.567, 0.919, 2.651]}
        scale={[-2.377, -1.918, -2.08]}
      >
        <mesh
          geometry={nodes["G-__558903_1"].geometry}
          material={materials["[Color_E05]"]}
        />
        <mesh
          geometry={nodes["G-__558903_2"].geometry}
          material={materials.Material}
        />
      </group>
      <mesh
        geometry={nodes["Component#1"].geometry}
        material={materials["[Color_000]"]}
        position={[20.973, -0.06, -2.23]}
        scale={1.872}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials["Black paint"]}
      />
      <mesh
        geometry={nodes.head_light.geometry}
        material={materials["[Resin Blue]"]}
      />
    </group>
  );
}

useGLTF.preload("/gallery-transformed.glb");
